### ISSUE TITLE
Incorrect values

### ISSUE THREAD

**Issue by jackkorber** [ekul135/Powerwall2PVOutput#6]
Do i need to perform any setup in the PVoutput page? (In addition to extended values)

My consumption and solar generation and export and import values are incorrect.

**Comment by ekul135** [comment]
No you shouldn't have to perform any setup.

Are you using the simple or datalogger?

**Comment by jackkorber** [comment]
I am using the datalogger.

Maybe I am confuse withe the definition of the parameter.
For the code , What is export, import and  consumption?

**Comment by ekul135** [comment]
I believe we don't send import or export values, only consumption.  PVOutput calculates import and export.

**Comment by jackkorber** [comment]
I think that the PVOutput page doesn’t take in consideration the energy to charge the batteries
